### ISSUE TITLE
real time deformation

### ISSUE THREAD

**Issue by yarosskopf** [eth-igl/GP2020-Assignments#33]
Hey guys

For exercise 1.5 our program has to achieve 10FPS. My solve() function takes ~38ms. So, that should be fine I guess. The program is, when I translate one handle-group with a quick mousestroke my solve() function gets called multiple times (counted 59 times last time I tried). The updated mesh only gets shown after all 59 solve() calls. Because the shown mesh only updates after all solve() calls, which takes about  2.5seconds, it doesnt feel "realtime" at all. Any idea how to fix this? Is there a way to restrain the callback_mouse_move to once every 50ms or so?

**Comment by JohnNYers** [comment]
A very hacky solution would be to call the **solve()** in the **callback_pre_draw()** method. However, you should implement a **solve_only_handle()** that only updates the handle position in your V and call it in the mouse_move function. This will resolve any translation errors due to 'unsync' updates of the handle positions.

**Comment by yarosskopf** [comment]
Thanks for your suggestion, it seems to work well enough. Thanks a lot :)
